# Generated by Django 3.1.7 on 2021-04-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('face_value', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
